gazebo_demo:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  joint1_position_controller:
    type: position_controllers/JointPositionController
    joint: joint_1
    #pid: {p: 100.0, i: 0.01, d: 10.0}

gazebo_demo/gazebo_ros_control/pid_gains:
  joint_1: {p: 100.0, i: 0.0, d: 10.0}
